name: Build and release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    env:
      TAG: ${{ inputs.tag || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ env.TAG }}
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: >
          dotnet publish .\NOWT\NOWT.csproj
          --configuration Release
          -p:PublishSingleFile=true
          --self-contained false -r win-x64
          -o ./inno
      - name: Download netcorecheck
        shell: pwsh
        run: |
          Invoke-WebRequest -URI https://go.microsoft.com/fwlink/?linkid=2135256 -OutFile .\inno\netcorecheck.exe
          Invoke-WebRequest -URI https://go.microsoft.com/fwlink/?linkid=2135504 -OutFile .\inno\netcorecheck_x64.exe
      - name: Download InnoSetup
        uses: pwall2222/inno-setup-download@v0.0.4
      - name: Package application
        run: ISCC.exe ./NOWT.iss
      - name: Rename installer
        shell: pwsh
        run: |
          Rename-Item ./inno/out/NOWT.exe NOWT-Installer.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./inno/out/NOWT-Installer.exe
            ./inno/NOWT.exe
          tag_name: ${{ env.TAG }}
