name: Generate Sponsors README

on:
  push:
    branches:
      - master
      - development-branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Add GitHub Sponsors to Readme
        uses: JamesIves/github-sponsors-readme-action@v1.1.0
        with:
          token: ${{ secrets.SECRETS }}
          file: 'README.md'
